### ISSUE TITLE
EqualSpacing breaks Navigation2D

### ISSUE THREAD

**Issue by incertia** [egasimus/xmonad-equalspacing#4]
If I split my windows like this with a BSP

```
+-------------------------------------------+
|            1           |         3        |
|                        |                  |
|                        |                  |
|                        |                  |
|                        |                  |
|                        |                  |
+------------------------+                  |
|            2           |                  |
|                        |                  |
|                        |                  |
|                        |                  |
|                        |                  |
|                        |                  |
+-------------------------------------------+
```

Navigation2D just gives up but splitting into 4 regions for a full depth 2 tree fixes everything. Not sure if this is a Navigation2D issue or something with the layout preventing Navigation2D from working.

**Comment by LSLeary** [comment]
@incertia So this issue is ancient and I just kinda happened to stumble upon it, but if you still care, then I imagine that what happened is you were using `lineNavigation`. As is described in the Navigation2D docs, `lineNavigation` literally just produces a line from the centre of the focused window out in the specified direction and navigates to the first window it intersects (with some tie-breaking when necessary). The strategy is incompatible with spacing/gaps, since that line (e.g. from window 3 to the left) will go right through the space between windows and find nothing, or skip past to another window. Depending on how recent your contrib is, Navigation2D provides some other strategies. I recommend `sideNavigation`, but if that's not available in your version then try in order: `hybridOf lineNavigation centerNavigation`; `hybridNavigation`; `centerNavigation`.

**Comment by incertia** [comment]
Yeah that's what I needed. Thanks.
